name: Build and Release Extension

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create extension zip
      run: |
        # Create a clean build directory
        mkdir -p build
        
        # Copy extension files (exclude .git, .github, and other non-extension files)
        cp manifest.json build/
        cp *.js build/
        cp *.html build/
        cp *.css build/
        cp -r images build/
        
        # Create the zip file
        cd build
        zip -r ../extension-${{ github.ref_name }}.zip .
        cd ..
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-zip
        path: extension-${{ github.ref_name }}.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: extension-${{ github.ref_name }}.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false